double **RKj(int i, int j, int Nx, double t, double dt, double *grid, double *deltagrid, double fel, double felb, double fml, double fnue, double fnueb, double fnum, double fer, double ferb, double fmr, double ful, double fulb, double ftl, double ftlb, double fdl, double fdlb, double fbl, double fblb, double fur, double furb, double ftr, double ftrb, double fdr, double fdrb, double fbr, double fbrb, double fh, double fwpl, double fwml, double fzl, double fwpp, double fwpm, double fwmp, double fwmm, double fzp, double fzm, double fphp, double fphm, double fzphp, double fzphm, double fgp, double fgm, double fhzl, double ftal, double ftalb, double ftar, double ftarb, double fnuta, double fnutab, double fcl, double fclb, double fcr, double fcrb, double fsl, double fslb, double **K, double a, double **alpha){
	K[i][j]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzdl(t,Ql)*Qzdl(t,Ql)*alphaz(t))*fel/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Ql)*Qzdl(t,Ql)*Ivffzt(t))*fel/(2*pi);
	K[i][j+Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzdl(t,Ql)*Qzdl(t,Ql)*alphaz(t))*felb/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Ql)*Qzdl(t,Ql)*Ivffzt(t))*felb/(2*pi);
	K[i][j+2*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzdl(t,Ql)*Qzdl(t,Ql)*alphaz(t))*fml/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Ql)*Qzdl(t,Ql)*Ivffzt(t))*fml/(2*pi);
	K[i][j+3*Nx]+=(log(1-grid[j])-a)*dt*2*regprop(t,mz)*theta(t,tz)*0.25*alphaz(t)*fnue/(2*pi)+dt*(0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*0.25*Ivffzt(t))*fnue/(2*pi);
	K[i][j+4*Nx]+=(log(1-grid[j])-a)*dt*2*regprop(t,mz)*theta(t,tz)*0.25*alphaz(t)*fnueb/(2*pi)+dt*(0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*0.25*Ivffzt(t))*fnueb/(2*pi);
	K[i][j+5*Nx]+=(log(1-grid[j])-a)*dt*2*regprop(t,mz)*theta(t,tz)*0.25*alphaz(t)*fnum/(2*pi)+dt*(0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*0.25*Ivffzt(t))*fnum/(2*pi);
	K[i][j+6*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzr(t,Ql)*Qzr(t,Ql)*alphaz(t))*fer/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+theta(t,tz)*alphaz(t)*Qzr(t,Ql)*Qzr(t,Ql)*Ivffzt(t))*fer/(2*pi);
	K[i][j+7*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzr(t,Ql)*Qzr(t,Ql)*alphaz(t))*ferb/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+theta(t,tz)*alphaz(t)*Qzr(t,Ql)*Qzr(t,Ql)*Ivffzt(t))*ferb/(2*pi);
	K[i][j+8*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzr(t,Ql)*Qzr(t,Ql)*alphaz(t))*fmr/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+theta(t,tz)*alphaz(t)*Qzr(t,Ql)*Qzr(t,Ql)*Ivffzt(t))*fmr/(2*pi);
	K[i][j+9*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzul(t,Qu)*Qzul(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*ful/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzul(t,Qu)*Qzul(t,Qu)*Ivffzt(t))*ful/(2*pi);
	K[i][j+10*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzul(t,Qu)*Qzul(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*fulb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzul(t,Qu)*Qzul(t,Qu)*Ivffzt(t))*fulb/(2*pi);
	K[i][j+11*Nx]+=theta(t,tt)*(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzul(t,Qu)*Qzul(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*ftl/(2*pi)+dt*theta(t,tt)*((Cf*alphas(t,alpha)+alphaem(t)*Qu*Qu)*Ivttv(t,0)+alphaz(t)*Qzul(t,Qu)*Qzul(t,Qu)*Ivttv(t,mz)+alpha2(t)*0.5*Ivtlbwt(t)+alphay(t,alpha)*0.5*(Ivtts(t,mh)+Ivtts(t,mz)))*ftl/(2*pi);
	K[i][j+12*Nx]+=theta(t,tt)*(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzul(t,Qu)*Qzul(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*ftlb/(2*pi)+dt*theta(t,tt)*((Cf*alphas(t,alpha)+alphaem(t)*Qu*Qu)*Ivttv(t,0)+alphaz(t)*Qzul(t,Qu)*Qzul(t,Qu)*Ivttv(t,mz)+alpha2(t)*0.5*Ivtlbwt(t)+alphay(t,alpha)*0.5*(Ivtts(t,mh)+Ivtts(t,mz)))*ftlb/(2*pi);
	K[i][j+13*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzdl(t,Qd)*Qzdl(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fdl/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Qd)*Qzdl(t,Qd)*Ivffzt(t))*fdl/(2*pi);
	K[i][j+14*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzdl(t,Qd)*Qzdl(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fdlb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Qd)*Qzdl(t,Qd)*Ivffzt(t))*fdlb/(2*pi);
	K[i][j+15*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzdl(t,Qd)*Qzdl(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fbl/(2*pi)+dt*(1.5*(Cf*alphas(t,alpha)+alphaem(t)*Qd*Qd)+theta(t,tz)*alphaz(t)*Qzdl(t,Qd)*Qzdl(t,Qd)*Ivffzt(t)+theta(t,tt)*alpha2(t)*0.5*Ivbltlwt(t)+theta(t,tt)*alphay(t,alpha)*Ivbltrwl(t))*fbl/(2*pi);
	K[i][j+16*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzdl(t,Qd)*Qzdl(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fblb/(2*pi)+dt*(1.5*(Cf*alphas(t,alpha)+alphaem(t)*Qd*Qd)+theta(t,tz)*alphaz(t)*Qzdl(t,Qd)*Qzdl(t,Qd)*Ivffzt(t)+theta(t,tt)*alpha2(t)*0.5*Ivbltlwt(t)+theta(t,tt)*alphay(t,alpha)*Ivbltrwl(t))*fblb/(2*pi);
	K[i][j+17*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzr(t,Qu)*Qzr(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*fur/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+theta(t,tz)*alphaz(t)*Qzr(t,Qu)*Qzr(t,Qu)*Ivffzt(t))*fur/(2*pi);
	K[i][j+18*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzr(t,Qu)*Qzr(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*furb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+theta(t,tz)*alphaz(t)*Qzr(t,Qu)*Qzr(t,Qu)*Ivffzt(t))*furb/(2*pi);
	K[i][j+19*Nx]+=theta(t,tt)*(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzr(t,Qu)*Qzr(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*ftr/(2*pi)+dt*theta(t,tt)*((Cf*alphas(t,alpha)+alphaem(t)*Qu*Qu)*Ivttv(t,0)+alphaz(t)*Qzr(t,Qu)*Qzr(t,Qu)*Ivttv(t,mz)+alpha2(t)*0.5*Ivtrbwl(t)+alphay(t,alpha)*0.5*(Ivtts(t,mh)+Ivtts(t,mz)))*ftr/(2*pi);
	K[i][j+20*Nx]+=theta(t,tt)*(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzr(t,Qu)*Qzr(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*ftrb/(2*pi)+dt*theta(t,tt)*((Cf*alphas(t,alpha)+alphaem(t)*Qu*Qu)*Ivttv(t,0)+alphaz(t)*Qzr(t,Qu)*Qzr(t,Qu)*Ivttv(t,mz)+alpha2(t)*0.5*Ivtrbwl(t)+alphay(t,alpha)*0.5*(Ivtts(t,mh)+Ivtts(t,mz)))*ftrb/(2*pi);
	K[i][j+21*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzr(t,Qd)*Qzr(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fdr/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+theta(t,tz)*alphaz(t)*Qzr(t,Qd)*Qzr(t,Qd)*Ivffzt(t))*fdr/(2*pi);
	K[i][j+22*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzr(t,Qd)*Qzr(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fdrb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+theta(t,tz)*alphaz(t)*Qzr(t,Qd)*Qzr(t,Qd)*Ivffzt(t))*fdrb/(2*pi);
	K[i][j+23*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzr(t,Qd)*Qzr(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fbr/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+theta(t,tz)*alphaz(t)*Qzr(t,Qd)*Qzr(t,Qd)*Ivffzt(t))*fbr/(2*pi);
	K[i][j+24*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzr(t,Qd)*Qzr(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fbrb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+theta(t,tz)*alphaz(t)*Qzr(t,Qd)*Qzr(t,Qd)*Ivffzt(t))*fbrb/(2*pi);
	K[i][j+25*Nx]+=dt*theta(t,th)*(theta(t,tt)*6*alphay(t,alpha)*Ivstt(t,mh)+alphaz(t)*0.25*Ivsvtvl(t,mh,mz)+alpha2(t)*0.5*Ivsvtvl(t,mh,mw))*fh/(2*pi);
	K[i][j+26*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)+regprop(t,mz)*alphaz(t)*theta(t,tz)*0.25*pow(c2w(t),2))*fwpl/(2*pi)+dt*(theta(t,tt)*3*alphay(t,alpha)*Ivwltb(t)+alpha2(t)*0.25*(theta(t,th)*Ivwlwts(t,mh)+theta(t,tz)*Ivwlwts(t,mz))+alphaem(t)*Ivwlwlvt(t,0)+theta(t,tz)*alphaz(t)*0.25*pow(c2w(t),2)*Ivwlwlvt(t,mz))*fwpl/(2*pi);
	K[i][j+27*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)+regprop(t,mz)*alphaz(t)*theta(t,tz)*0.25*pow(c2w(t),2))*fwml/(2*pi)+dt*(theta(t,tt)*3*alphay(t,alpha)*Ivwltb(t)+alpha2(t)*0.25*(theta(t,th)*Ivwlwts(t,mh)+theta(t,tz)*Ivwlwts(t,mz))+alphaem(t)*Ivwlwlvt(t,0)+theta(t,tz)*alphaz(t)*0.25*pow(c2w(t),2)*Ivwlwlvt(t,mz))*fwml/(2*pi);
	K[i][j+28*Nx]+=dt*theta(t,tz)*(theta(t,tt)*6*alphay(t,alpha)*Ivstt(t,mz)+theta(t,th)*alphaz(t)*0.25*Ivzlhzt(t)+alpha2(t)*0.5*Ivsvtvl(t,mz,mw))*fzl/(2*pi);
	K[i][j+29*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)+regprop(t,mz)*alpha2(t)*theta(t,tz)*pow(cw(t),2))*fwpp/(2*pi)+dt*(alpha2(t)*4.5*Ivvtff0(t,mw)+alpha2(t)*1.5*theta(t,tt)*Ivwptb(t)+alpha2(t)*0.25*(theta(t,th)*Ivwtwls(t,mh)+theta(t,tz)*Ivwtwls(t,mz))+alphaem(t)*Ivwtwtvt(t,0)+alpha2(t)*cw(t)*cw(t)*Ivwtwtvt(t,mz))*fwpp/(2*pi);
	K[i][j+30*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)+regprop(t,mz)*alpha2(t)*theta(t,tz)*pow(cw(t),2))*fwpm/(2*pi)+dt*(alpha2(t)*4.5*Ivvtff0(t,mw)+alpha2(t)*1.5*theta(t,tt)*Ivwmtb(t)+alpha2(t)*0.25*(theta(t,th)*Ivwtwls(t,mh)+theta(t,tz)*Ivwtwls(t,mz))+alphaem(t)*Ivwtwtvt(t,0)+alpha2(t)*cw(t)*cw(t)*Ivwtwtvt(t,mz))*fwpm/(2*pi);
	K[i][j+31*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)+regprop(t,mz)*alpha2(t)*theta(t,tz)*pow(cw(t),2))*fwmp/(2*pi)+dt*(alpha2(t)*4.5*Ivvtff0(t,mw)+alpha2(t)*1.5*theta(t,tt)*Ivwmtb(t)+alpha2(t)*0.25*(theta(t,th)*Ivwtwls(t,mh)+theta(t,tz)*Ivwtwls(t,mz))+alphaem(t)*Ivwtwtvt(t,0)+alpha2(t)*cw(t)*cw(t)*Ivwtwtvt(t,mz))*fwmp/(2*pi);
	K[i][j+32*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)+regprop(t,mz)*alpha2(t)*theta(t,tz)*pow(cw(t),2))*fwmm/(2*pi)+dt*(alpha2(t)*4.5*Ivvtff0(t,mw)+alpha2(t)*1.5*theta(t,tt)*Ivwptb(t)+alpha2(t)*0.25*(theta(t,th)*Ivwtwls(t,mh)+theta(t,tz)*Ivwtwls(t,mz))+alphaem(t)*Ivwtwtvt(t,0)+alpha2(t)*cw(t)*cw(t)*Ivwtwtvt(t,mz))*fwmm/(2*pi);
	K[i][j+33*Nx]+=dt*theta(t,tz)*(alphaz(t)*(5.25-10*sw(t)*sw(t)+40*pow(sw(t),4)/3)*Ivvtff0(t,mz)+theta(t,tt)*(0.25-2*sw(t)*sw(t)/3+8*pow(sw(t),4)/9)*Ivzttt(t)+theta(t,th)*alphaz(t)*0.25*Ivzthzl(t)+2*alphaz(t)*(pow(cw(t),4)*Ivztwtwt(t)+0.25*c2w(t)*c2w(t)*Ivztwlwl(t)))*fzp/(2*pi);
	K[i][j+34*Nx]+=dt*theta(t,tz)*(alphaz(t)*(5.25-10*sw(t)*sw(t)+40*pow(sw(t),4)/3)*Ivvtff0(t,mz)+theta(t,tt)*(0.25-2*sw(t)*sw(t)/3+8*pow(sw(t),4)/9)*Ivzttt(t)+theta(t,th)*alphaz(t)*0.25*Ivzthzl(t)+2*alphaz(t)*(pow(cw(t),4)*Ivztwtwt(t)+0.25*c2w(t)*c2w(t)*Ivztwlwl(t)))*fzm/(2*pi);
	K[i][j+35*Nx]+=dt*alphaem(t)*(-(40+8*theta(t,tt)*prop2(t,0,mt,mt,1))/9-prop2(t,0,mw,mw,1)/6+2*prop2(t,0,mw,mw,1)*Ivphwtwt(t))*fphp/(2*pi);
	K[i][j+36*Nx]+=dt*alphaem(t)*(-(40+8*theta(t,tt)*prop2(t,0,mt,mt,1))/9-prop2(t,0,mw,mw,1)/6+2*prop2(t,0,mw,mw,1)*Ivphwtwt(t))*fphm/(2*pi);
	K[i][j+37*Nx]+=dt*theta(t,tz)*0.5*(alphaem(t)*(-(40+8*theta(t,tt)*prop2(t,0,mt,mt,1))/9-prop2(t,0,mw,mw,1)/6+2*prop2(t,0,mw,mw,1)*Ivphwtwt(t))+alphaz(t)*(5.25-10*sw(t)*sw(t)+40*pow(sw(t),4)/3)*Ivvtff0(t,mz)+theta(t,tt)*(0.25-2*sw(t)*sw(t)/3+8*pow(sw(t),4)/9)*Ivzttt(t)+theta(t,th)*alphaz(t)*0.25*Ivzthzl(t)+2*alphaz(t)*(pow(cw(t),4)*Ivztwtwt(t)+0.25*c2w(t)*c2w(t)*Ivztwlwl(t)))*fzphp/(2*pi);
	K[i][j+38*Nx]+=dt*theta(t,tz)*0.5*(alphaem(t)*(-(40+8*theta(t,tt)*prop2(t,0,mt,mt,1))/9-prop2(t,0,mw,mw,1)/6+2*prop2(t,0,mw,mw,1)*Ivphwtwt(t))+alphaz(t)*(5.25-10*sw(t)*sw(t)+40*pow(sw(t),4)/3)*Ivvtff0(t,mz)+theta(t,tt)*(0.25-2*sw(t)*sw(t)/3+8*pow(sw(t),4)/9)*Ivzttt(t)+theta(t,th)*alphaz(t)*0.25*Ivzthzl(t)+2*alphaz(t)*(pow(cw(t),4)*Ivztwtwt(t)+0.25*c2w(t)*c2w(t)*Ivztwlwl(t)))*fzphm/(2*pi);
	K[i][j+39*Nx]+=(log(1-grid[j])-a)*dt*alphas(t,alpha)*6*fgp/(2*pi)+dt*alphas(t,alpha)*(5.5-(5+theta(t,tt)*prop2(t,0,mt,mt,1))/3)*fgp/(2*pi);
	K[i][j+40*Nx]+=(log(1-grid[j])-a)*dt*alphas(t,alpha)*6*fgm/(2*pi)+dt*alphas(t,alpha)*(5.5-(5+theta(t,tt)*prop2(t,0,mt,mt,1))/3)*fgm/(2*pi);
	K[i][j+41*Nx]+=dt*theta(t,tz)*0.5*(theta(t,tt)*6*alphay(t,alpha)*Ivstt(t,mh)+alphaz(t)*0.25*Ivsvtvl(t,mh,mz)+alpha2(t)*0.5*Ivsvtvl(t,mh,mw)+theta(t,tt)*6*alphay(t,alpha)*Ivstt(t,mz)+theta(t,th)*alphaz(t)*0.25*Ivzlhzt(t)+alpha2(t)*0.5*Ivsvtvl(t,mz,mw))*fhzl/(2*pi);
	K[i][j+42*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzdl(t,Ql)*Qzdl(t,Ql)*alphaz(t))*ftal/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Ql)*Qzdl(t,Ql)*Ivffzt(t))*ftal/(2*pi);
	K[i][j+43*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzdl(t,Ql)*Qzdl(t,Ql)*alphaz(t))*ftalb/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Ql)*Qzdl(t,Ql)*Ivffzt(t))*ftalb/(2*pi);
	K[i][j+44*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzr(t,Ql)*Qzr(t,Ql)*alphaz(t))*ftar/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+theta(t,tz)*alphaz(t)*Qzr(t,Ql)*Qzr(t,Ql)*Ivffzt(t))*ftar/(2*pi);
	K[i][j+45*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Ql*Ql+regprop(t,mz)*theta(t,tz)*Qzr(t,Ql)*Qzr(t,Ql)*alphaz(t))*ftarb/(2*pi)+dt*(1.5*alphaem(t)*Ql*Ql+theta(t,tz)*alphaz(t)*Qzr(t,Ql)*Qzr(t,Ql)*Ivffzt(t))*ftarb/(2*pi);
	K[i][j+46*Nx]+=(log(1-grid[j])-a)*dt*2*regprop(t,mz)*theta(t,tz)*0.25*alphaz(t)*fnuta/(2*pi)+dt*(0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*0.25*Ivffzt(t))*fnuta/(2*pi);
	K[i][j+47*Nx]+=(log(1-grid[j])-a)*dt*2*regprop(t,mz)*theta(t,tz)*0.25*alphaz(t)*fnutab/(2*pi)+dt*(0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*0.25*Ivffzt(t))*fnutab/(2*pi);
	K[i][j+48*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzul(t,Qu)*Qzul(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*fcl/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzul(t,Qu)*Qzul(t,Qu)*Ivffzt(t))*fcl/(2*pi);
	K[i][j+49*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzul(t,Qu)*Qzul(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*fclb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzul(t,Qu)*Qzul(t,Qu)*Ivffzt(t))*fclb/(2*pi);
	K[i][j+50*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzr(t,Qu)*Qzr(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*fcr/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+theta(t,tz)*alphaz(t)*Qzr(t,Qu)*Qzr(t,Qu)*Ivffzt(t))*fcr/(2*pi);
	K[i][j+51*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qu*Qu+regprop(t,mz)*theta(t,tz)*Qzr(t,Qu)*Qzr(t,Qu)*alphaz(t)+Cf*alphas(t,alpha))*fcrb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qu*Qu+theta(t,tz)*alphaz(t)*Qzr(t,Qu)*Qzr(t,Qu)*Ivffzt(t))*fcrb/(2*pi);
	K[i][j+52*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzdl(t,Qd)*Qzdl(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fsl/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Qd)*Qzdl(t,Qd)*Ivffzt(t))*fsl/(2*pi);
	K[i][j+53*Nx]+=(log(1-grid[j])-a)*dt*2*(alphaem(t)*Qd*Qd+regprop(t,mz)*theta(t,tz)*Qzdl(t,Qd)*Qzdl(t,Qd)*alphaz(t)+Cf*alphas(t,alpha))*fslb/(2*pi)+dt*(1.5*Cf*alphas(t,alpha)+1.5*alphaem(t)*Qd*Qd+0.5*alpha2(t)*Ivffwt(t)+theta(t,tz)*alphaz(t)*Qzdl(t,Qd)*Qzdl(t,Qd)*Ivffzt(t))*fslb/(2*pi);
	return K;
}

/*Imposition of momentum conservation*/
double Lt(double *x, double *dx, int n, int i, double **fel, double **felb, double **fml, double **ftal, double **ftalb, double **fnue, double **fnueb, double **fnum, double **fnuta, double **fnutab, double **fer, double **ferb, double **fmr, double **ftar, double **ftarb, double **ful, double **fulb, double **fcl, double **fclb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fsl, double **fslb, double **fbl, double **fblb, double **fur, double **furb, double **fcr, double **fcrb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fgp, double **fgm){
	double L;
	L = 1;
	int j;
	for(j=0;j<n-1;j++){
		L-=x[j]*dx[j]*(fel[i][j]+fml[i][j]+ftal[i][j]+2*felb[i][j]+ftalb[i][j]+fer[i][j]+fmr[i][j]+ftar[i][j]+2*ferb[i][j]+ftarb[i][j]+fnue[i][j]+fnum[i][j]+fnuta[i][j]+2*fnueb[i][j]+fnutab[i][j]+ful[i][j]+fulb[i][j]+fcl[i][j]+fclb[i][j]+ftl[i][j]+ftlb[i][j]+fur[i][j]+furb[i][j]+fcr[i][j]+fcrb[i][j]+ftr[i][j]+ftrb[i][j]+fdl[i][j]+fdlb[i][j]+fsl[i][j]+fslb[i][j]+2*fdr[i][j]+2*fdrb[i][j]+fbl[i][j]+fblb[i][j]+fbr[i][j]+fbrb[i][j]+fh[i][j]+fwpl[i][j]+fwpp[i][j]+fwpm[i][j]+fwml[i][j]+fwmp[i][j]+fwmm[i][j]+fzl[i][j]+fzp[i][j]+fzm[i][j]+fphp[i][j]+fphm[i][j]+fgp[i][j]+fgm[i][j]);
	}
	L/=2;
	return L;
}
