int e5FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int eb5FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mu5FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mub5FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int e6FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",0.0); /*tL*/
	fprintf(output, "%e	",0.0); /*tR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",0.0); /*tLb*/
	fprintf(output, "%e	",0.0); /*tRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int eb6FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",0.0); /*tL*/
	fprintf(output, "%e	",0.0); /*tR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",0.0); /*tLb*/
	fprintf(output, "%e	",0.0); /*tRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mu6FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",0.0); /*tL*/
	fprintf(output, "%e	",0.0); /*tR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",0.0); /*tLb*/
	fprintf(output, "%e	",0.0); /*tRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mub6FS0(int i, int j, FILE *output, double *grid, double **fe, double **fm, double **fu, double **fd, double **fb, double **fph, double **fg, double **fc, double **ftau){
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eR*/
	fprintf(output, "%e	",0.0);  /*nue*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muL*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*muR*/
	fprintf(output, "%e	",0.0); /*numu*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taL*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taR*/
	fprintf(output, "%e	",0.0); /*nuta*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eLb*/
	fprintf(output, "%e	",grid[i]*fe[j][i]/2); /*eRb*/
	fprintf(output, "%e	",0.0); /*nueb*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muLb*/
	fprintf(output, "%e	",grid[i]*fm[j][i]/2); /*muRb*/
	fprintf(output, "%e	",0.0); /*numub*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftau[j][i]/2); /*taRb*/
	fprintf(output, "%e	",0.0); /*nutab*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dR*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uL*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sL*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sR*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cL*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cR*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bL*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bR*/
	fprintf(output, "%e	",0.0); /*tL*/
	fprintf(output, "%e	",0.0); /*tR*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*dRb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uLb*/
	fprintf(output, "%e	",grid[i]*fu[j][i]/2); /*uRb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sLb*/
	fprintf(output, "%e	",grid[i]*fd[j][i]/2); /*sRb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cLb*/
	fprintf(output, "%e	",grid[i]*fc[j][i]/2); /*cRb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bLb*/
	fprintf(output, "%e	",grid[i]*fb[j][i]/2); /*bRb*/
	fprintf(output, "%e	",0.0); /*tLb*/
	fprintf(output, "%e	",0.0); /*tRb*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gp*/
	fprintf(output, "%e	",grid[i]*fg[j][i]/2); /*gm*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gap*/
	fprintf(output, "%e	",grid[i]*fph[j][i]/2); /*gam*/
	fprintf(output, "%e	",0.0); /*Zp*/
	fprintf(output, "%e	",0.0); /*Zm*/
	fprintf(output, "%e	",0.0); /*ZL*/
	fprintf(output, "%e	",0.0); /*Zgap*/
	fprintf(output, "%e	",0.0); /*Zgam*/
	fprintf(output, "%e	",0.0); /*Wpp*/
	fprintf(output, "%e	",0.0); /*Wpm*/
	fprintf(output, "%e	",0.0); /*WpL*/
	fprintf(output, "%e	",0.0); /*Wmp*/
	fprintf(output, "%e	",0.0); /*Wmm*/
	fprintf(output, "%e	",0.0); /*WmL*/
	fprintf(output, "%e	",0.0); /*h*/
	fprintf(output, "%e	",0.0); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int e5FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*fml[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*fel[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int eb5FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*felb[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*fml[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*fel[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mu5FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*fel[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*fml[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mub5FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*felb[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*fel[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*fml[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int e6FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*fml[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*fel[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*ftl[j][i]); /*tL*/
	fprintf(output, "%e	",grid[i]*ftr[j][i]); /*tR*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*ftlb[j][i]); /*tLb*/
	fprintf(output, "%e	",grid[i]*ftrb[j][i]); /*tRb*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int eb6FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*felb[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*fml[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*fel[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*ftlb[j][i]); /*tL*/
	fprintf(output, "%e	",grid[i]*ftrb[j][i]); /*tR*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*ftl[j][i]); /*tLb*/
	fprintf(output, "%e	",grid[i]*ftr[j][i]); /*tRb*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mu6FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*fel[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*fml[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*ftl[j][i]); /*tL*/
	fprintf(output, "%e	",grid[i]*ftr[j][i]); /*tR*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*ftlb[j][i]); /*tLb*/
	fprintf(output, "%e	",grid[i]*ftrb[j][i]); /*tRb*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}

int mub6FS(int i, int j, FILE *output, double *grid, double **fel, double **felb, double **fml, double **fnue, double **fnueb, double **fnum, double **fer, double **ferb, double **fmr, double **ful, double **fulb, double **ftl, double **ftlb, double **fdl, double **fdlb, double **fbl, double **fblb, double **fur, double **furb, double **ftr, double **ftrb, double **fdr, double **fdrb, double **fbr, double **fbrb, double **fh, double **fwpl, double **fwml, double **fzl, double **fwpp, double **fwpm, double **fwmp, double **fwmm, double **fzp, double **fzm, double **fphp, double **fphm, double **fzphp, double **fzphm, double **fgp, double **fgm, double **fhzl, double **ftal, double **ftalb, double **ftar, double **ftarb, double **fnuta, double **fnutab, double **fcl, double **fclb, double **fcr, double **fcrb, double **fsl, double **fslb){
	fprintf(output, "%e	",grid[i]*felb[j][i]); /*eL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*eR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*nue*/
	fprintf(output, "%e	",grid[i]*felb[j][i]);  /*muL*/
	fprintf(output, "%e	",grid[i]*ferb[j][i]); /*muR*/
	fprintf(output, "%e	",grid[i]*fnueb[j][i]); /*numu*/
	fprintf(output, "%e	",grid[i]*ftalb[j][i]); /*taL*/
	fprintf(output, "%e	",grid[i]*ftarb[j][i]); /*taR*/
	fprintf(output, "%e	",grid[i]*fnutab[j][i]); /*nuta*/
	fprintf(output, "%e	",grid[i]*fel[j][i]); /*eLb*/
	fprintf(output, "%e	",grid[i]*fer[j][i]); /*eRb*/
	fprintf(output, "%e	",grid[i]*fnue[j][i]); /*nueb*/
	fprintf(output, "%e	",grid[i]*fml[j][i]); /*muLb*/
	fprintf(output, "%e	",grid[i]*fmr[j][i]); /*muRb*/
	fprintf(output, "%e	",grid[i]*fnum[j][i]); /*numub*/
	fprintf(output, "%e	",grid[i]*ftal[j][i]); /*taLb*/
	fprintf(output, "%e	",grid[i]*ftar[j][i]); /*taRb*/
	fprintf(output, "%e	",grid[i]*fnuta[j][i]); /*nutab*/
	fprintf(output, "%e	",grid[i]*fdlb[j][i]); /*dL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*dR*/
	fprintf(output, "%e	",grid[i]*fulb[j][i]); /*uL*/
	fprintf(output, "%e	",grid[i]*furb[j][i]); /*uR*/
	fprintf(output, "%e	",grid[i]*fslb[j][i]); /*sL*/
	fprintf(output, "%e	",grid[i]*fdrb[j][i]); /*sR*/
	fprintf(output, "%e	",grid[i]*fclb[j][i]); /*cL*/
	fprintf(output, "%e	",grid[i]*fcrb[j][i]); /*cR*/
	fprintf(output, "%e	",grid[i]*fblb[j][i]); /*bL*/
	fprintf(output, "%e	",grid[i]*fbrb[j][i]); /*bR*/
	fprintf(output, "%e	",grid[i]*ftlb[j][i]); /*tL*/
	fprintf(output, "%e	",grid[i]*ftrb[j][i]); /*tR*/
	fprintf(output, "%e	",grid[i]*fdl[j][i]); /*dLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*dRb*/
	fprintf(output, "%e	",grid[i]*ful[j][i]); /*uLb*/
	fprintf(output, "%e	",grid[i]*fur[j][i]); /*uRb*/
	fprintf(output, "%e	",grid[i]*fsl[j][i]); /*sLb*/
	fprintf(output, "%e	",grid[i]*fdr[j][i]); /*sRb*/
	fprintf(output, "%e	",grid[i]*fcl[j][i]); /*cLb*/
	fprintf(output, "%e	",grid[i]*fcr[j][i]); /*cRb*/
	fprintf(output, "%e	",grid[i]*fbl[j][i]); /*bLb*/
	fprintf(output, "%e	",grid[i]*fbr[j][i]); /*bRb*/
	fprintf(output, "%e	",grid[i]*ftl[j][i]); /*tLb*/
	fprintf(output, "%e	",grid[i]*ftr[j][i]); /*tRb*/
	fprintf(output, "%e	",grid[i]*fgm[j][i]); /*gp*/
	fprintf(output, "%e	",grid[i]*fgp[j][i]); /*gm*/
	fprintf(output, "%e	",grid[i]*fphm[j][i]); /*gap*/
	fprintf(output, "%e	",grid[i]*fphp[j][i]); /*gam*/
	fprintf(output, "%e	",grid[i]*fzm[j][i]); /*Zp*/
	fprintf(output, "%e	",grid[i]*fzp[j][i]); /*Zm*/
	fprintf(output, "%e	",grid[i]*fzl[j][i]); /*ZL*/
	fprintf(output, "%e	",grid[i]*fzphm[j][i]); /*Zgap*/
	fprintf(output, "%e	",grid[i]*fzphp[j][i]); /*Zgam*/
	fprintf(output, "%e	",grid[i]*fwmm[j][i]); /*Wpp*/
	fprintf(output, "%e	",grid[i]*fwmp[j][i]); /*Wpm*/
	fprintf(output, "%e	",grid[i]*fwml[j][i]); /*WpL*/
	fprintf(output, "%e	",grid[i]*fwpm[j][i]); /*Wmp*/
	fprintf(output, "%e	",grid[i]*fwpp[j][i]); /*Wmm*/
	fprintf(output, "%e	",grid[i]*fwpl[j][i]); /*WmL*/
	fprintf(output, "%e	",grid[i]*fh[j][i]); /*h*/
	fprintf(output, "%e	",grid[i]*fhzl[j][i]); /*hZL*/
	fprintf(output, "\n");
	return 0;
}
